Fix docker-compose integration tests
momentum-mod/website pull request #562
Opened 2021-11-19 16:14 UTC by murgle2

2021-11-29 22:48 UTC, Hona commented
Please resolve the merge conflicts.

Also, it looks like the github actions aren't running on the latest commit here?

2021-11-29 23:16 UTC, murgle2 commented
> Please resolve the merge conflicts.
> 
> Also, it looks like the github actions aren't running on the latest commit here?

Resolved!

2021-11-30 01:17 UTC, Hona commented
Is this ready for test?

2021-11-30 01:20 UTC, murgle2 commented
> 

Yep! It just needs that other PR (#561) so it will test the docker part correctly

2021-11-30 05:07 UTC, Gocnak commented
Server tests aren't running right now. It's building the containers fine but the output is pretty much meaningless (if it's actually running tests, which considering GitHub actions moves on immediately, I don't think so):
![image](https://user-images.githubusercontent.com/5162166/143989001-227c5ae5-6741-4dfd-b132-10259f50622e.png)

2021-11-30 05:12 UTC, Gocnak requested changes
Server tests aren't running right now. It's building the containers fine but the output is pretty much meaningless (if it's actually running tests, which considering GitHub actions moves on immediately, I don't think so):
![image](https://user-images.githubusercontent.com/5162166/143989001-227c5ae5-6741-4dfd-b132-10259f50622e.png)

I would also prefer for the Docker containers to use a Yarn cache so we aren't waiting minutes again. 
![image](https://user-images.githubusercontent.com/5162166/143989129-7e56e67e-ed35-4cee-b68d-a4f319671a2e.png)

This has been an issue since #559, I'm not sure what the rush was to get it in. @TheNerdMan also pointed out that there's no frontend dev (with auto-reloading) container either, which significantly hinders development progress.

2021-11-30 18:44 UTC, murgle2 commented
Server tests now shows tests outputs and correctly uses the exit code to determine test results. 

The benefit of dockerizing the backend is very significant in comparison to the frontend. The current dev workflow involves running yarn install and npm start for the frontend, which does autoreloading and communicates with the dockerized backend, which also autoreloads. 

If there's a strong demand for it, I can dockerize the frontend as well.

2021-12-01 02:46 UTC, Gocnak requested changes
Yeah the frontend just being a local dev environment is fine! The backend was the more tedious setup anyways, so great that it's properly containerized now.

I'd say caching is absolutely still worth it but can be done in another branch. A few nits here but I'm otherwise fine to merge this in after.

2021-12-01 02:46 UTC, Gocnak commented on server/package.json
> +    "test": "chmod +x ../scripts/wait-for-it.sh && ../scripts/wait-for-it.sh db:3306 --timeout=60 -- mocha --exit --timeout 45000"
I think the `"test"` command should still be the `mocha --exit --timeout` stuff, and this specifically should be `test-docker`:

```suggestion
    "test": "mocha --exit --timeout 45000",
    "test-docker": "chmod +x ../scripts/wait-for-it.sh && ../scripts/wait-for-it.sh db:3306 --timeout=60 -- npm run test"
```

That way we're separating out the actual test command from the docker entrypoint command.

2021-12-01 02:46 UTC, Gocnak commented on docker-compose.test.yml
> +    entrypoint: "npm run test"
And with the other suggestion:
```suggestion
    entrypoint: "npm run test-docker"
```

2021-12-01 06:21 UTC, Gocnak approved these changes

2021-12-01 06:21 UTC, merged