Feat/issue 233 loading indicators
momentum-mod/website pull request #568
Opened 2021-12-12 02:30 UTC by KJelles

2021-12-12 02:32 UTC, KJelles commented
Open for feedback @Gocnak

2021-12-17 07:01 UTC, Gocnak requested changes

2021-12-17 07:01 UTC, Gocnak commented on client/src/app/pages/dashboard/profile/user-profile.component.ts
> +import { NbToastrService } from "@nebular/theme";
Your formatter seems to have broken our strings, we prefer single quotation strings here (`'`), with double being only used in CSS/HTML files

2021-12-22 03:04 UTC, Gocnak approved these changes
Great work!

2021-12-22 03:05 UTC, merged