Feature/delete runs
momentum-mod/website pull request #580
Opened 2021-12-31 18:40 UTC by murgle2

Allow admins to delete a users run and shift the other runs to fill in the rank gap. Checks if the user has a next best run and inserts that run.

Notes:
- Does not reset stats gained once the run is deleted
- If the next best run replay does not exist on server, the replay will only be accessible locally
- If a user has tied times as their next best run (same total ticks), then the next best run may not be the most recent
- Since tickrate datatype was changed to decimal this will require db sync

Todo:
- Update leaderboard list UI once deleted
- More testing

2022-02-11 21:14 UTC, Hona requested changes
Looks pretty good!

2022-02-11 21:14 UTC, Hona commented on server/src/models/run.js
> +			if (nextBestRun) {
Make this a guard statement

2024-03-01 21:57 UTC, tsa96 commented
Closing, as this is way too outdated to ever be useful. I really appreciate the work done here and sorry that this can't be used. It's very frustrating how disorganized the website work was in this time period, pretty sure we knew the backend was going to need rewriting at this point already, and shouldn't have encouraged people work on issues like this.

2024-03-01 21:57 UTC, closed without merging

2024-03-01 21:58 UTC, tsa96 commented
Also, I will never accept a PR containing a Gitmoji