Map info page
momentum-mod/website pull request #906
Opened 2024-02-08 14:00 UTC by tsa96

Total redesign of main map page, including leaderboards, submission details, and reviews.

Have some map submission form changes in here as well that I couldn't separate out that easily.

Closes #829

2024-02-20 08:35 UTC, tsa96 commented
Oops, I'll do a Prettier run and re-push once someone reviews!

2024-03-05 14:43 UTC, GordiNoki requested changes

2024-03-05 14:43 UTC, GordiNoki commented on apps/frontend/src/app/theme/styles.css
I'm not quite sure what exactly, but something broke the `.top-right-toolbar` in profile component. It has position absolute and was realtive to m-card for whatever reason, but now it's relative to body, and I have no idea why. The solution would be to add `position: relative` to m-card, but it may add other issues.

2024-03-05 16:07 UTC, tsa96 commented on apps/frontend/src/app/theme/styles.css
The `profile` component is still using old styling stuff. There's an issue to redo it [here](https://github.com/momentum-mod/website/issues/893), in the meantime we don't care if it breaks. Especially when it has garbage classes like this:
```css
.top-right-toolbar {
  right: 1.25rem;
  position: absolute;
  z-index: 500;
}
```

2024-03-05 16:25 UTC, GordiNoki approved these changes

2024-03-05 16:26 UTC, merged