Notification system
momentum-mod/website pull request #914
Opened 2024-02-26 14:48 UTC by benjl

Don't skip ci this time pls

2024-02-26 17:16 UTC, tsa96 requested changes

2024-02-26 17:16 UTC, tsa96 commented on apps/backend-e2e/src/maps-2.e2e-spec.ts
> +        expect(notifs).toHaveLength(1);
grrrr

2024-05-30 20:41 UTC, tsa96 requested changes
Sorry for taking a while to get to this, please tag me here / ping me on Discord if I miss an update to a PR! Usually aim to review web stuff in 2-3 days at most.

2024-05-30 20:41 UTC, tsa96 commented on apps/backend/src/app/modules/notifications/notifications.service.ts
> +          throw new BadRequestException('notifIDs must contain numbers only');
`IntCsvQueryProperty` is already doing this check

2024-05-30 20:41 UTC, tsa96 commented on apps/backend/src/app/modules/notifications/notifications.service.ts
> +          throw new BadRequestException('notifIDs must contain numbers only');
IMO cleaner to throw if `(!query.all && !query.notifIDs))` then in `deleteMany` do `id: query.notifIDs ? { in: query.notifIDs } : undefined`

2024-05-30 20:41 UTC, tsa96 commented on apps/backend-e2e/src/notifications.e2e-spec.ts
> +    it('should not delete a map testing request notification', async () => {
Still here. Sorry to nag about this but saves us random format cleanup commits in the future.

2024-06-07 22:38 UTC, tsa96 commented on apps/backend/src/app/modules/notifications/notifications.service.ts
> +          throw new BadRequestException('notifIDs must contain numbers only');
You just mentioned to me that IntCsvQueryProperty isn't handling NaN right, reminder for you to take a look at that!

2025-08-26 16:59 UTC, AshenCinders commented
Also need to call sendNotifications for the other notification types (excluding WR achieved, not doing that yet).
But feel free to check already for issues.

~~schema announcement comment is currently wrong btw~~

2025-08-27 12:23 UTC, AshenCinders commented
<img width="669" height="267" alt="vivaldi_ObAZPQbmGV" src="https://github.com/user-attachments/assets/fdbc25ee-242f-43c5-bb61-fddf381e18db" />

This test only fails when ran together with other tests.
Seems to be a concurrency/shared data issue?
@GordiNoki would you mind taking a look?

2025-08-27 18:57 UTC, AshenCinders commented on apps/backend/src/app/modules/notifications/notifications.service.ts
> +          throw new BadRequestException('notifIDs must contain numbers only');
I'm not sure what this is about, so would be good if you could check?

2025-08-27 19:07 UTC, AshenCinders commented
Not doing WR and Announcement notifs now, I've added issues for them.
The rest is pretty much done.

Only need to figure out the failing discord e2e test

2025-08-30 19:10 UTC, tsa96 commented on apps/backend/src/app/modules/notifications/notifications.service.ts
> +          throw new BadRequestException('notifIDs must contain numbers only');
Probably worth adding `IsInt({ each: true })` to the decorator, then we should be good.

2025-08-31 15:05 UTC, AshenCinders commented
@tsa96 feel free to merge, you'll need to restart backend anyway

2025-09-01 07:59 UTC, merged