Fix recent changes with docker and env variables
momentum-mod/website pull request #936
Opened 2024-04-20 18:11 UTC by GordiNoki

The solution for cookies is not great, but works for dev and should probably work for prod

2024-04-20 19:12 UTC, tsa96 requested changes

2024-04-20 19:12 UTC, tsa96 commented on docker-compose.yml
> +      - .env
This should be in the override!

2024-04-20 19:18 UTC, GordiNoki commented on docker-compose.yml
> +      - .env
Done

2024-04-21 16:32 UTC, tsa96 commented
Closing in favour of #937

2024-04-21 16:32 UTC, closed without merging