Fix production prep issues
momentum-mod/website pull request #937
Opened 2024-04-21 16:32 UTC by tsa96

Supercedes #936
- Fixed .env file not being loaded by dev docker environment (thanks Gordi)
- Changed how URLs/domains are handled
- Disabled ESLint commit hook because it takes an absolutely absurd amount of time. CI checks and encouraging people to use the editor plugin is enough IMO.
- Docker Image publishing *hopefully* works, followed your recommendation Nick.
- Random faff

2024-04-21 16:50 UTC, GordiNoki requested changes

2024-04-21 16:50 UTC, GordiNoki commented on docker-compose.override.yml
Probably mixed up my env_file entries and yours

2024-04-23 12:40 UTC, GordiNoki approved these changes

2024-04-23 17:43 UTC, Gocnak approved these changes
It's probably not an issue yet but we may want to optimize the RUN steps in the docker file to minimize the size of the image. These changes are good so it's a future problem

2024-04-23 17:44 UTC, merged